// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: topurls.proto

package analytics

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopUrlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *TopUrlsRequest) Reset() {
	*x = TopUrlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topurls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUrlsRequest) ProtoMessage() {}

func (x *TopUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topurls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUrlsRequest.ProtoReflect.Descriptor instead.
func (*TopUrlsRequest) Descriptor() ([]byte, []int) {
	return file_topurls_proto_rawDescGZIP(), []int{0}
}

func (x *TopUrlsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TopUrlsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Next          int64 `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Previous      int64 `protobuf:"varint,2,opt,name=previous,proto3" json:"previous,omitempty"`
	RecordPerPage int64 `protobuf:"varint,3,opt,name=recordPerPage,proto3" json:"recordPerPage,omitempty"`
	CurrentPage   int64 `protobuf:"varint,4,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	TotalPage     int64 `protobuf:"varint,5,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topurls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_topurls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_topurls_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetNext() int64 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *Pagination) GetPrevious() int64 {
	if x != nil {
		return x.Previous
	}
	return 0
}

func (x *Pagination) GetRecordPerPage() int64 {
	if x != nil {
		return x.RecordPerPage
	}
	return 0
}

func (x *Pagination) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type TopUrlData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl     string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
	ShortUrl    string `protobuf:"bytes,2,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
	FollowCount int64  `protobuf:"varint,3,opt,name=followCount,proto3" json:"followCount,omitempty"`
	CreateCount int64  `protobuf:"varint,4,opt,name=createCount,proto3" json:"createCount,omitempty"`
}

func (x *TopUrlData) Reset() {
	*x = TopUrlData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topurls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopUrlData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUrlData) ProtoMessage() {}

func (x *TopUrlData) ProtoReflect() protoreflect.Message {
	mi := &file_topurls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUrlData.ProtoReflect.Descriptor instead.
func (*TopUrlData) Descriptor() ([]byte, []int) {
	return file_topurls_proto_rawDescGZIP(), []int{2}
}

func (x *TopUrlData) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *TopUrlData) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *TopUrlData) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *TopUrlData) GetCreateCount() int64 {
	if x != nil {
		return x.CreateCount
	}
	return 0
}

type TopUrlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopUrlData []*TopUrlData `protobuf:"bytes,1,rep,name=topUrlData,proto3" json:"topUrlData,omitempty"`
	Pagination *Pagination   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *TopUrlsResponse) Reset() {
	*x = TopUrlsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topurls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUrlsResponse) ProtoMessage() {}

func (x *TopUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topurls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUrlsResponse.ProtoReflect.Descriptor instead.
func (*TopUrlsResponse) Descriptor() ([]byte, []int) {
	return file_topurls_proto_rawDescGZIP(), []int{3}
}

func (x *TopUrlsResponse) GetTopUrlData() []*TopUrlData {
	if x != nil {
		return x.TopUrlData
	}
	return nil
}

func (x *TopUrlsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_topurls_proto protoreflect.FileDescriptor

var file_topurls_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0e, 0x54, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0xa2, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x6e, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50,
	0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x54, 0x6f, 0x70, 0x55, 0x72,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x7f, 0x0a, 0x0f, 0x54, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x74,
	0x6f, 0x70, 0x55, 0x72, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x32, 0x52, 0x0a, 0x09, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x12, 0x45, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x74, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_topurls_proto_rawDescOnce sync.Once
	file_topurls_proto_rawDescData = file_topurls_proto_rawDesc
)

func file_topurls_proto_rawDescGZIP() []byte {
	file_topurls_proto_rawDescOnce.Do(func() {
		file_topurls_proto_rawDescData = protoimpl.X.CompressGZIP(file_topurls_proto_rawDescData)
	})
	return file_topurls_proto_rawDescData
}

var file_topurls_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_topurls_proto_goTypes = []interface{}{
	(*TopUrlsRequest)(nil),  // 0: analytics.TopUrlsRequest
	(*Pagination)(nil),      // 1: analytics.Pagination
	(*TopUrlData)(nil),      // 2: analytics.TopUrlData
	(*TopUrlsResponse)(nil), // 3: analytics.TopUrlsResponse
}
var file_topurls_proto_depIdxs = []int32{
	2, // 0: analytics.TopUrlsResponse.topUrlData:type_name -> analytics.TopUrlData
	1, // 1: analytics.TopUrlsResponse.pagination:type_name -> analytics.Pagination
	0, // 2: analytics.Analytics.GetTopUrls:input_type -> analytics.TopUrlsRequest
	3, // 3: analytics.Analytics.GetTopUrls:output_type -> analytics.TopUrlsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_topurls_proto_init() }
func file_topurls_proto_init() {
	if File_topurls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_topurls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopUrlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topurls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topurls_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopUrlData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topurls_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopUrlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topurls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topurls_proto_goTypes,
		DependencyIndexes: file_topurls_proto_depIdxs,
		MessageInfos:      file_topurls_proto_msgTypes,
	}.Build()
	File_topurls_proto = out.File
	file_topurls_proto_rawDesc = nil
	file_topurls_proto_goTypes = nil
	file_topurls_proto_depIdxs = nil
}
