// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UrlClient is an autogenerated mock type for the UrlClient type
type UrlClient struct {
	mock.Mock
}

// FollowUrl provides a mock function with given fields: ctx, shortUrl
func (_m *UrlClient) FollowUrl(ctx context.Context, shortUrl string) (string, error) {
	ret := _m.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for FollowUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenUrl provides a mock function with given fields: ctx, longUrl
func (_m *UrlClient) ShortenUrl(ctx context.Context, longUrl string) (string, error) {
	ret := _m.Called(ctx, longUrl)

	if len(ret) == 0 {
		panic("no return value specified for ShortenUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, longUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, longUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, longUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlClient creates a new instance of UrlClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlClient {
	mock := &UrlClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
