// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: pkg/proto/url.proto

package url

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *LongUrlRequest) Reset() {
	*x = LongUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrlRequest) ProtoMessage() {}

func (x *LongUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrlRequest.ProtoReflect.Descriptor instead.
func (*LongUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_url_proto_rawDescGZIP(), []int{0}
}

func (x *LongUrlRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type UrlDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl  string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
	ShortUrl string `protobuf:"bytes,2,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *UrlDataResponse) Reset() {
	*x = UrlDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlDataResponse) ProtoMessage() {}

func (x *UrlDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlDataResponse.ProtoReflect.Descriptor instead.
func (*UrlDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_url_proto_rawDescGZIP(), []int{1}
}

func (x *UrlDataResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *UrlDataResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *ShortUrlRequest) Reset() {
	*x = ShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_url_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrlRequest) ProtoMessage() {}

func (x *ShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_url_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrlRequest.ProtoReflect.Descriptor instead.
func (*ShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_url_proto_rawDescGZIP(), []int{2}
}

func (x *ShortUrlRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type LongUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *LongUrlResponse) Reset() {
	*x = LongUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_url_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrlResponse) ProtoMessage() {}

func (x *LongUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_url_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrlResponse.ProtoReflect.Descriptor instead.
func (*LongUrlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_url_proto_rawDescGZIP(), []int{3}
}

func (x *LongUrlResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_pkg_proto_url_proto protoreflect.FileDescriptor

var file_pkg_proto_url_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x0e, 0x4c, 0x6f,
	0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x47, 0x0a, 0x0f, 0x55, 0x72, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e,
	0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67,
	0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22,
	0x2d, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2b,
	0x0a, 0x0f, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x32, 0x7b, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c,
	0x12, 0x13, 0x2e, 0x75, 0x72, 0x6c, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x75, 0x72, 0x6c, 0x2e, 0x55, 0x72, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x2e, 0x75, 0x72, 0x6c,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x75, 0x72, 0x6c, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x75,
	0x72, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_url_proto_rawDescOnce sync.Once
	file_pkg_proto_url_proto_rawDescData = file_pkg_proto_url_proto_rawDesc
)

func file_pkg_proto_url_proto_rawDescGZIP() []byte {
	file_pkg_proto_url_proto_rawDescOnce.Do(func() {
		file_pkg_proto_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_url_proto_rawDescData)
	})
	return file_pkg_proto_url_proto_rawDescData
}

var file_pkg_proto_url_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_url_proto_goTypes = []interface{}{
	(*LongUrlRequest)(nil),  // 0: url.LongUrlRequest
	(*UrlDataResponse)(nil), // 1: url.UrlDataResponse
	(*ShortUrlRequest)(nil), // 2: url.ShortUrlRequest
	(*LongUrlResponse)(nil), // 3: url.LongUrlResponse
}
var file_pkg_proto_url_proto_depIdxs = []int32{
	0, // 0: url.Url.ShortenUrl:input_type -> url.LongUrlRequest
	2, // 1: url.Url.FollowUrl:input_type -> url.ShortUrlRequest
	1, // 2: url.Url.ShortenUrl:output_type -> url.UrlDataResponse
	3, // 3: url.Url.FollowUrl:output_type -> url.LongUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_url_proto_init() }
func file_pkg_proto_url_proto_init() {
	if File_pkg_proto_url_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_url_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_url_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_url_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_url_proto_goTypes,
		DependencyIndexes: file_pkg_proto_url_proto_depIdxs,
		MessageInfos:      file_pkg_proto_url_proto_msgTypes,
	}.Build()
	File_pkg_proto_url_proto = out.File
	file_pkg_proto_url_proto_rawDesc = nil
	file_pkg_proto_url_proto_goTypes = nil
	file_pkg_proto_url_proto_depIdxs = nil
}
