// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "CoolUrlShortener/internal/repository/models"

	mock "github.com/stretchr/testify/mock"
)

// EventsProducer is an autogenerated mock type for the EventsProducer type
type EventsProducer struct {
	mock.Mock
}

// ProduceEvent provides a mock function with given fields: event
func (_m *EventsProducer) ProduceEvent(event models.URLEvent) {
	_m.Called(event)
}

// NewEventsProducer creates a new instance of EventsProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsProducer {
	mock := &EventsProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
