// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// URLCache is an autogenerated mock type for the URLCache type
type URLCache struct {
	mock.Mock
}

// GetLongURL provides a mock function with given fields: ctx, shortURL
func (_m *URLCache) GetLongURL(ctx context.Context, shortURL string) (string, error) {
	ret := _m.Called(ctx, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for GetLongURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLongURL provides a mock function with given fields: ctx, shortURL, longURL
func (_m *URLCache) SetLongURL(ctx context.Context, shortURL string, longURL string) error {
	ret := _m.Called(ctx, shortURL, longURL)

	if len(ret) == 0 {
		panic("no return value specified for SetLongURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, shortURL, longURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLCache creates a new instance of URLCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLCache {
	mock := &URLCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
