// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	domain "CoolUrlShortener/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UrlRepo is an autogenerated mock type for the UrlRepo type
type UrlRepo struct {
	mock.Mock
}

// GetLongURL provides a mock function with given fields: ctx, shortUrl
func (_m *UrlRepo) GetLongURL(ctx context.Context, shortUrl string) (string, error) {
	ret := _m.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetLongURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShortURLByLongURL provides a mock function with given fields: ctx, longURL
func (_m *UrlRepo) GetShortURLByLongURL(ctx context.Context, longURL string) (string, error) {
	ret := _m.Called(ctx, longURL)

	if len(ret) == 0 {
		panic("no return value specified for GetShortURLByLongURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, longURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, longURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, longURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveURL provides a mock function with given fields: ctx, urlData
func (_m *UrlRepo) SaveURL(ctx context.Context, urlData domain.URLData) error {
	ret := _m.Called(ctx, urlData)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.URLData) error); ok {
		r0 = rf(ctx, urlData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlRepo creates a new instance of UrlRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRepo {
	mock := &UrlRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
