definitions:
  dto.LongURLData:
    properties:
      long_url:
        type: string
    type: object
  dto.Pagination:
    properties:
      current_page:
        type: integer
      next:
        type: integer
      previous:
        type: integer
      record_per_page:
        type: integer
      total_page:
        type: integer
    type: object
  dto.TopURLData:
    properties:
      create_count:
        type: integer
      follow_count:
        type: integer
      long_url:
        type: string
      short_url:
        type: string
    type: object
  dto.TopURLDataResponse:
    properties:
      pagination:
        $ref: '#/definitions/dto.Pagination'
      top_url_data:
        items:
          $ref: '#/definitions/dto.TopURLData'
        type: array
    type: object
  dto.URlData:
    properties:
      long_url:
        type: string
      short_url:
        type: string
    type: object
  response.Body:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: API Server for shorten urls
  title: CoolURLShortener API
  version: "1.0"
paths:
  /{short_url}:
    get:
      description: Принимает короткую ссылку в path параметрах и производит редирект
        на исходную ссылку
      operationId: follow-url
      parameters:
      - description: короткая ссылка
        in: query
        name: id
        required: true
        type: string
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
      summary: Редирект с короткой ссылки на исходную ссылку
      tags:
      - url
  /api/save_url:
    options:
      description: Возвращает информацию по хедерам Access-Control-Request-Method,
        Access-Control-Request-Headers, Origin
      operationId: options-save-url
      responses:
        "200":
          description: ""
      summary: Получение описания параметров соединения с сервером
      tags:
      - options
    post:
      consumes:
      - application/json
      description: Принимает исходную ссылку, создает короткую ссылку и возвращает
        короткую ссылку
      operationId: save-url
      parameters:
      - description: Длинная ссылка
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.LongURLData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.URlData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
      summary: Создание и сохранение короткой ссылки по исходной ссылки
      tags:
      - url
  /api/top_urls:
    get:
      consumes:
      - application/json
      description: Принимает page и limit. Возвращает список популярных url. Поддерживает
        пагинацию
      operationId: get-top-urls
      parameters:
      - description: Страница
        in: query
        name: page
        type: integer
      - description: Максимальное количество url на странице
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TopURLDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
      summary: Получение списка популярных url
      tags:
      - url
swagger: "2.0"
