name: Build and Push services to server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input:'
        required: true
        default: "Run"

jobs:
  job1:
    name: Build and push service
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      FRONTEND_NAME: ${{ secrets.DOCKER_FRONTED_NAME }}
      URL_SHORTENER_SERVICE_NAME: ${{ secrets.DOCKER_URL_SHORTENER_SERVICE_NAME }}
      ANALYTICS_SERVICE_NAME: ${{ secrets.DOCKER_ANALYTICS_SERVICE_NAME }}
      API_GATEWAY_NAME: ${{ secrets.DOCKER_API_GATEWAY_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build frontend image
        run: docker build -t $LOGIN/$FRONTEND_NAME:latest ./frontend
      - name: Build URL Shortener Service image
        run: docker build -t $LOGIN/$URL_SHORTENER_SERVICE_NAME:latest ./url_shortener_service
      - name: Build Analytics Service image
        run: docker build -t $LOGIN/$ANALYTICS_SERVICE_NAME:latest ./analytics_service
      - name: Build API Gateway image
        run: docker build -t $LOGIN/$API_GATEWAY_NAME:latest ./api_gateway

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

      - name: Push frontend image
        run: docker push $LOGIN/$FRONTEND_NAME:latest
      - name: Push URL Shortener Service image
        run: docker push $LOGIN/$URL_SHORTENER_SERVICE_NAME:latest
      - name: Push Analytics Service image
        run: docker push $LOGIN/$ANALYTICS_SERVICE_NAME:latest
      - name: Push API Gateway image
        run: docker push $LOGIN/$API_GATEWAY_NAME:latest

  job2:
    name: Publish
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.VIRTUAL_IP }}
          user: ${{ secrets.VIRTUAL_LOGIN }}
          key: ${{ secrets.SERVER_KEY }}
          run: |
            cd url_shortener
            sudo docker compose pull
            sudo docker compose up -d